# Generated by Django 3.0.5 on 2020-04-04 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='article_url',
        ),
        migrations.AddField(
            model_name='articleurl',
            name='article_title',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='newsfeed.Title'),
        ),
    ]
