# Generated by Django 3.0.5 on 2020-04-04 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0002_auto_20200404_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200)),
                ('article_date', models.DateTimeField(verbose_name='date published')),
                ('article_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='rating',
            name='title',
        ),
        migrations.DeleteModel(
            name='ArticleURL',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
        migrations.AddField(
            model_name='article',
            name='article_publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsfeed.Publisher'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsfeed.Rating'),
        ),
    ]
