# Generated by Django 2.2.12 on 2020-04-05 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsfeed', '0004_auto_20200404_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_rating',
            new_name='article_negative_votes',
        ),
        migrations.AddField(
            model_name='article',
            name='article_positive_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=200)),
                ('comment_positive_votes', models.IntegerField(default=0)),
                ('comment_negative_votes', models.IntegerField(default=0)),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
