# Generated by Django 2.2.12 on 2020-04-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0009_auto_20200406_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_comment',
        ),
        migrations.AddField(
            model_name='article',
            name='article_comments',
            field=models.ManyToManyField(blank=True, null=True, to='newsfeed.Comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_comments',
            field=models.ManyToManyField(blank=True, null=True, related_name='_comment_comment_comments_+', to='newsfeed.Comment'),
        ),
    ]
