# Generated by Django 2.2.12 on 2020-04-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0010_auto_20200406_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_comments',
            field=models.ManyToManyField(blank=True, to='newsfeed.Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_comments',
            field=models.ManyToManyField(blank=True, related_name='_comment_comment_comments_+', to='newsfeed.Comment'),
        ),
    ]
