# Generated by Django 2.2.12 on 2020-04-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0012_auto_20200406_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_comments',
        ),
        migrations.AlterField(
            model_name='article',
            name='article_comments',
            field=models.ManyToManyField(blank=True, to='newsfeed.Comment'),
        ),
    ]
