# Generated by Django 2.2.12 on 2020-04-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0013_auto_20200406_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_comments',
            field=models.ManyToManyField(blank=True, related_name='_comment_comment_comments_+', to='newsfeed.Comment'),
        ),
    ]
